# Generated by Django 3.1.3 on 2020-11-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='carousel_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='carousel_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
