# Generated by Django 3.1.3 on 2020-12-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='service_body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_title',
            field=models.CharField(default='teste', max_length=50),
            preserve_default=False,
        ),
    ]
