# Generated by Django 3.1.4 on 2021-01-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageservices',
            name='link',
            field=models.CharField(blank=True, help_text='Adicionar link para uma URL, por exemplo: /contato', max_length=255, null=True),
        ),
    ]
