# Generated by Django 3.1.4 on 2020-12-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
        ('home', '0002_auto_20201211_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='member_link',
            field=models.ForeignKey(blank=True, help_text='Page to link to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailtrans.translatablepage', verbose_name='Link to be a member'),
        ),
    ]
