# Generated by Django 3.1.4 on 2020-12-18 11:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
        ('home', '0005_homepage_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='member_link',
            field=models.ForeignKey(blank=True, help_text='Page to link to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailtrans.translatablepage', verbose_name='Link para ser um membro'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_body',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Corpo do serviço'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_title',
            field=models.CharField(max_length=50, verbose_name='Título do serviço'),
        ),
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='description_color',
            field=models.CharField(blank=True, help_text='Por exemplo: #ffffff', max_length=7, verbose_name='Cor da descrição'),
        ),
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='title_color',
            field=models.CharField(blank=True, help_text='Por exemplo: #ffffff', max_length=7, verbose_name='Cor do título'),
        ),
        migrations.AlterField(
            model_name='homepageservices',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='homepagewhychooseus',
            name='description',
            field=models.CharField(max_length=254, verbose_name='Descrição'),
        ),
    ]
