# Generated by Django 3.1.4 on 2020-12-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
        ('home', '0006_auto_20201218_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='member_link',
            field=models.ForeignKey(blank=True, help_text='Adicionar link para uma página', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailtrans.translatablepage', verbose_name='Link para ser um membro'),
        ),
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='link',
            field=models.CharField(blank=True, help_text='Adicionar link para uma URL, por exemplo: /contato', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homepageservices',
            name='link',
            field=models.ForeignKey(blank=True, help_text='Adicionar link para uma página', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailtrans.translatablepage', verbose_name='Link'),
        ),
    ]
