# Generated by Django 3.1.4 on 2021-01-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepageitem',
            name='link_url',
        ),
        migrations.AddField(
            model_name='coursepageitem',
            name='btn_form_01',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='coursepageitem',
            name='btn_form_02',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='coursepageitem',
            name='form_01',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Formulário'),
        ),
        migrations.AddField(
            model_name='coursepageitem',
            name='form_02',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Formulário'),
        ),
    ]
