# Generated by Django 3.1.4 on 2020-12-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201210_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='introduction',
            field=models.TextField(default='a', help_text='Brief description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Link to Linkedin', max_length=254),
        ),
    ]
