# Generated by Django 3.1.4 on 2021-01-17 16:05

import base.models
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210108_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='document',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='video',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Broadcast link'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='coursepageitem',
            name='btn_form_01',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto do botão'),
        ),
        migrations.AlterField(
            model_name='coursepageitem',
            name='btn_form_02',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto do botão'),
        ),
        migrations.CreateModel(
            name='CourseMaterialVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('video', models.FileField(blank=True, max_length=254, null=True, upload_to=base.models.course_directory_path, verbose_name='Vídeo')),
                ('course_material', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_material_video', to='base.coursematerial')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseMaterialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('document', models.FileField(blank=True, max_length=254, null=True, upload_to=base.models.course_directory_path, verbose_name='Documento')),
                ('course_material', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_material_document', to='base.coursematerial')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
