# Generated by Django 3.1.4 on 2021-01-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210117_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link da transmissão'),
        ),
    ]
