# Generated by Django 3.1.4 on 2020-12-22 14:32

from django.db import migrations, models
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201218_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(verbose_name='Término')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Término')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('price2x', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor em 2x')),
                ('price3x', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor em 3x')),
                ('vacancies', models.IntegerField(verbose_name='Vagas')),
                ('registered', models.IntegerField(blank=True, null=True, verbose_name='Inscritos')),
                ('description', wagtail.core.fields.RichTextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Equipe'},
        ),
    ]
