# Generated by Django 3.1.4 on 2021-02-23 20:12

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailtrans', '0009_create_initial_language'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('base', '0005_teammember_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseUserInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_button', models.BooleanField(default=False, verbose_name='Show payment button')),
            ],
        ),
        migrations.RemoveField(
            model_name='coursepageitem',
            name='course_page',
        ),
        migrations.RemoveField(
            model_name='coursepageitem',
            name='link_page',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'verbose_name': 'Course material', 'verbose_name_plural': 'Course materials'},
        ),
        migrations.AlterModelOptions(
            name='footertext',
            options={'verbose_name_plural': 'Footer Text'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Team'},
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='course',
            name='introduction',
            field=models.CharField(default='teste', max_length=254, verbose_name='Introduction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price4x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price 4x'),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('individual', 'Individual'), ('group', 'Group'), ('recorded', 'Recorded')], default='group', max_length=15, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_booking',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pre-booking'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price2x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price 2x'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price3x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price 3x'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registered',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Registered'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='vacancies',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vacancies'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Broadcast link'),
        ),
        migrations.AlterField(
            model_name='coursematerialvideo',
            name='video',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=base.models.course_directory_path, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='payment_id',
            field=models.CharField(blank=True, max_length=254, verbose_name='Payment Id'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='payment_note',
            field=models.CharField(blank=True, max_length=254, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='payment_status',
            field=models.CharField(blank=True, max_length=254, verbose_name='Payment status'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='status',
            field=models.CharField(choices=[('enroll', 'Enroll'), ('pre-booking', 'Pre-booking')], max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Page to link to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailtrans.translatablepage'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL to link to, e.g. /contato', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='show_when',
            field=models.CharField(choices=[('always', 'Always'), ('logged_in', 'When logged in'), ('not_logged_in', 'When not logged in')], default='always', max_length=15),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='introduction',
            field=models.TextField(help_text='Brief description'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='job_title',
            field=models.CharField(blank=True, max_length=254, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Link to Linkedin', max_length=254),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(blank=True, default=10, verbose_name='Position'),
        ),
        migrations.DeleteModel(
            name='CoursePage',
        ),
        migrations.DeleteModel(
            name='CoursePageItem',
        ),
        migrations.AddField(
            model_name='courseuserinterview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='courseuserinterview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_courses', to='base.course'),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_coursetag_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='base.CourseTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
