# Generated by Django 3.1.4 on 2020-12-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_courseuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registered',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Inscritos'),
        ),
    ]
