# Generated by Django 3.1.4 on 2021-04-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_courseusercoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price1x',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price2x',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price3x',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price4x',
        ),
        migrations.AddField(
            model_name='courseuser',
            name='coupon_used',
            field=models.CharField(blank=True, max_length=254, verbose_name='Coupon'),
        ),
    ]
