# Generated by Django 3.1.4 on 2021-05-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210430_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_booking',
            field=models.IntegerField(blank=True, default=0, verbose_name='Pre-booking'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registered',
            field=models.IntegerField(blank=True, default=0, verbose_name='Registered'),
        ),
    ]
