# Generated by Django 3.1.4 on 2020-12-30 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
        ('base', '0009_coursepage_coursepageitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepage',
            options={'verbose_name': 'Página do curso', 'verbose_name_plural': 'Página do curso'},
        ),
        migrations.AddField(
            model_name='course',
            name='pre_booking',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pré-reserva'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseuser',
            name='status',
            field=models.CharField(choices=[('enroll', 'Fazer inscrição'), ('pre-booking', 'Pré-reserva')], default='enroll', max_length=30, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='course',
            name='vacancies',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vagas'),
        ),
        migrations.AlterField(
            model_name='coursepageitem',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Adicionar link para uma página', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailtrans.translatablepage'),
        ),
        migrations.AlterField(
            model_name='coursepageitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Adicionar link para uma URL, por exemplo: /contato', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Adicionar link para uma página', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailtrans.translatablepage'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Adicionar link para uma URL, por exemplo: /contato', max_length=500, null=True),
        ),
    ]
