# Generated by Django 3.1.4 on 2022-10-06 20:13

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210503_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='info',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Info for authenticated users'),
        ),
    ]
