# Generated by Django 3.1.4 on 2021-01-02 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_auto_20201230_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='payment_id',
            field=models.CharField(blank=True, max_length=254, verbose_name='Id do pagamento'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='payment_note',
            field=models.CharField(blank=True, max_length=254, verbose_name='Obs'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='payment_status',
            field=models.CharField(blank=True, max_length=254, verbose_name='Status do pagamento'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='status',
            field=models.CharField(choices=[('enroll', 'Inscrição'), ('pre-booking', 'Pré-reserva')], max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
