# Generated by Django 3.1.4 on 2023-03-04 19:22

import base.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
        ('base', '0011_course_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'verbose_name': 'Material do curso', 'verbose_name_plural': 'Materiais do curso'},
        ),
        migrations.AlterModelOptions(
            name='courseusercoupon',
            options={'verbose_name': 'Cupom', 'verbose_name_plural': 'Cupons'},
        ),
        migrations.AlterModelOptions(
            name='footertext',
            options={'verbose_name_plural': 'Texto do rodapé'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Equipe'},
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Informações para usuários autenticados'),
        ),
        migrations.AlterField(
            model_name='course',
            name='introduction',
            field=models.CharField(max_length=254, verbose_name='Introdução'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_booking',
            field=models.IntegerField(blank=True, default=0, verbose_name='Pré-reserva'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registered',
            field=models.IntegerField(blank=True, default=0, verbose_name='Inscritos'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('individual', 'Individual'), ('group', 'Grupo'), ('recorded', 'Gravado')], max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='vacancies',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vagas'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link da transmissão'),
        ),
        migrations.AlterField(
            model_name='coursematerialvideo',
            name='video',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=base.models.course_directory_path, verbose_name='Vídeo'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='coupon_used',
            field=models.CharField(blank=True, max_length=254, verbose_name='Cupom'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='payment_id',
            field=models.CharField(blank=True, max_length=254, verbose_name='Id do pagamento'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='payment_note',
            field=models.CharField(blank=True, max_length=254, verbose_name='Obs'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='payment_status',
            field=models.CharField(blank=True, max_length=254, verbose_name='Status do pagamento'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='status',
            field=models.CharField(choices=[('enroll', 'Inscrição'), ('pre-booking', 'Pré-reserva')], max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='courseusercoupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[&]', inverse_match=True)], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='courseusercoupon',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='courseusercoupon',
            name='discount',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='courseusercoupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Válido a partir de'),
        ),
        migrations.AlterField(
            model_name='courseusercoupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Válido até'),
        ),
        migrations.AlterField(
            model_name='courseuserinterview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='courseuserinterview',
            name='show_button',
            field=models.BooleanField(default=False, verbose_name='Mostrar botão de pagamento'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Texto para descrever a página'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Adicionar link para uma página', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailtrans.translatablepage'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Adicionar link para uma URL, por exemplo: /contato', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='show_when',
            field=models.CharField(choices=[('always', 'Sempre'), ('logged_in', 'Quando logado'), ('not_logged_in', 'Quando não estiver logado')], default='always', max_length=15),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Texto para descrever a página'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='introduction',
            field=models.TextField(help_text='Breve descrição'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='job_title',
            field=models.CharField(blank=True, max_length=254, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Link para o Linkedin', max_length=254),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(blank=True, default=10, verbose_name='Posição'),
        ),
    ]
