# Generated by Django 3.1.4 on 2023-06-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20230304_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Free class'),
        ),
    ]
