name: Django CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: sabia
          POSTGRES_PASSWORD: sabia
          POSTGRES_BD: sabia
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Rename file
      run: |
        mv sabia/settings/local_example.py sabia/settings/local.py
    - name: Run Tests
      run: |
        python manage.py test
