# Generated by Django 3.1.3 on 2020-11-25 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number starting with (DDD)', regex='^\\+(\\(?\\d{2}\\)?\\s)?(\\d{4,5}\\-\\d{4})$')], verbose_name='Phone'),
        ),
    ]
