# Generated by Django 3.1.4 on 2020-12-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20201223_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='newsletter',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='yes', max_length=3),
        ),
    ]
